---
name: hmu_library_signup_web_interface
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  country_picker: ^2.0.8
  cupertino_icons: ^1.0.4
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_styled_toast: ^2.0.0
  google_fonts: ^2.1.0
  url_launcher: ^6.0.12
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
